### Reference: Deep Learning by Ian Goodfellow, Yoshua Bengio and Aaron Courville

The __XOR__ function takes in two binary values as input, and it can summarized as below:

$$ f(x_1, x_2)=   \left\{
\begin{array}{ll}
      0, \hspace{0.2cm} if \hspace{0.2cm} x_1 = 0 \hspace{0.2cm} and \hspace{0.2cm} x_2 = 0\\
      1, \hspace{0.2cm} if \hspace{0.2cm} x_1 = 1 \hspace{0.2cm} and \hspace{0.2cm} x_2 = 0\\
      1, \hspace{0.2cm} if \hspace{0.2cm} x_1 = 0 \hspace{0.2cm} and \hspace{0.2cm} x_2 = 1\\
      0, \hspace{0.2cm} if \hspace{0.2cm} x_1 = 1 \hspace{0.2cm} and \hspace{0.2cm} x_2 = 1
\end{array} 
\right.  $$



Let us assume that the XOR function provides us the target function $y = f^{*}(x)$ that we want to learn. 

Let our model be the function defined by $y = f(x; \theta)$ and our learning algorithm will adapt the parameters $\theta$ to make $f$ as similar as possible to $f^{*}$.

We want our model to perform correctly on the four points $X = \bigl\{[0,0]^{T}, [0,1]^{T}, [1,0]^{T}, [1,1]^{T}\bigl\}$.

We can treat this problem as a regression problem and use mean squared error (MSE) as our loss function. Evaluated on the whole dataset the MSE loss function is,

$$
J(\theta) = \frac{1}{4} \sum_{x \in X} (f^{*}(x) - f(x; \theta))^{2}
$$

which we get from the main form the MSE loss,

$$
MSE_{test} = \frac{1}{m} \sum_{i} (\hat{y}^{(test)} - y^{(test)})^{2}_{i} = \frac{1}{m} \sum_{i} \big\| (\hat{y}^{(test)} - y^{(test)}) \big\|^{2}_2
$$

Now we will choose the form of our model $f(x;\theta)$. Suppose that we choose a linear model, with $\theta$ consisting of $w$ and $b$. Our model is then defined to be,
$$
f(x;w, b) = x^{T}w + b
$$

### Normal Equation

To minizime the loss function we will use the normal equations. Here we derive the normal equations for the linear model,
$$
\hat{y} = w^{T}x
$$

To minizime $MSE_{train}$ we will solve for the point where its gradient is 0,

$$
\begin{align*}
\nabla_w MSE_{train} &= 0 \\[0.2cm]
\nabla_w \frac{1}{m} \big\| \hat{y}^{(train)} - y^{(train)} \big\|^{2}_2 & = 0 \\[0.2cm]
\frac{1}{m} \nabla_w \big\| X^{(train)}w - y^{(train)} \big\|^{2}_2 & = 0 \\[0.2cm]
\nabla_w \bigl(X^{(train)}w - y^{(train)} \bigl)^{T} \bigl(X^{(train)}w - y^{(train)}) & = 0 \\[0.2cm]
\nabla_w \bigl(w^{T}X^{(train)^{T}}X^{(train)}w - 2w^{T}X^{(train)^T}y^{(train)} + y^{(train)^{T}} y^{(train)} \bigl) & = 0 \\[0.2cm]
2 w (X^{(train)^T} X^{(train)}) - 2 (X^{(train)^T}y^{(train)}) & = 0 \\[0.2cm]
\therefore w & = (X^{(train)^{T}} X^{(train)})^{-1} \cdot (X^{(train)^{T}}y^{(train)})
\end{align*}
$$

This is the normal equation for the linear model $\hat{y} = w^{T}x$, from which we can derive the values of the parameters $w$, in simpler terms it takes the form,

$$
w = (X^{T}X)^{-1} \cdot (X^{T}y)
$$

### Applying Normal Equation

The above formula is for the linear model $\hat{y} = w^{T}x$. But in our case we have taken a bias vector $b$, to which we assign $1$ for all entries, as is the usual practice.

Here, the value of the matrix $X$ after adding the bias $b$ is,

$$
X = \begin{bmatrix}
0 & 0 & 1\\
0 & 1 & 1\\
1 & 0 & 1\\
1 & 1 & 1
\end{bmatrix} \hspace{1cm}
X^{T} = \begin{bmatrix}
0 & 0 & 1 & 1 \\
0 & 1 & 0 & 1 \\
1 & 1 & 1 & 1
\end{bmatrix}
$$

$$
X^{T}X = \begin{bmatrix}
2 & 1 & 2 \\
1 & 2 & 2 \\
2 & 2 & 4
\end{bmatrix}
$$

$$
y = \begin{bmatrix}
0 \\
1 \\
1 \\
0
\end{bmatrix}
$$

Computing $(X^{T}X)^{-1} \cdot (X^{T}y)$, we get,
$$
\begin{bmatrix}
0.0 \\
0.0 \\
0.5 \\
\end{bmatrix}
$$

The first two values corresponds to the parameters $w_1$ and $w_2$ and the third value is of the bias $b$. Hence, we get,
$$
w_1 = 0 \\
w_2 = 0 \\
b = \frac{1}{2}
$$

It can be seen that the linear model simply outputs $\frac{1}{2}$ everywhere. Thus this linear model is not able to solve the problem of approximating the XOR function. To overcome this we will introduce a very simple feedforward network with one hidden layer containing two hidden units. This feedforward network has a vector of hidden units $h$ that are computed by a function $f^{1}(x; W, c)$.

The values of these hidden units are then used as input for a second layer, which is the output layer of the network. The output layer is still just a linear regression model, but now it is applied to $h$ rather than $x$. The network now contains two functions chained together:
$$
h = f^{(1)}(x; W, c) \\
y = f^{(2)}(h; w, b)
$$

The entire model is given by:

$$
f(x; W, c, w, b) = f^{(2)}(f^{(1)}(x))
$$

We will use a nonlinear function to describe the features. Most neural networks do so using an __affine__ transformation controlled by learned parameters, followed by a fixed nonlinear function called an activation function.

We define $h = g(W^{T}x + c)$, where $W$ provides the weights of a linear transformation and $c$ the biases. The activation function h is typically chosen to be a function that is applied element wise, with  $h_i = g(x^{T}W_{:, i} + c)$.

Here we will choose ReLU, which is given by, $g(z) = max\bigl\{0, z\bigl\}$. 

The complete neural network is then given by, 

$$
f(x; W, c, w, b) = w^{T} max\bigl\{0, W^{T}x + c\bigl\} + b 
$$

### The Neural Network Based Solution to the XOR problem

We are choosing the matrices and vectors $W$, $c$, $w$ and $b$ as below. In a real implementation these values would be randomized in the beggining and a gradiend-based learning method will gradually converge to these values during the training of the neural network. It should be noted that for this particular problem this set of parameters provides the global minimum. The convergence point of gradient descent depends on the initial values of the parameters. In practice, gradient descent would usually not find clean, easily understood, integer-valued solutions like the one presented here.

$$
W = \begin{bmatrix}
1 & 1 \\
1 & 1
\end{bmatrix},\\[0.2cm]
c = \begin{bmatrix}
0 \\
-1
\end{bmatrix},\\[0.2cm]
w = \begin{bmatrix}
1 \\
-2
\end{bmatrix} \\[0.2cm]
b = 0
$$

#### Hidden Layer

The hidden layer performs the following operations:

Operation 1: Multiply $X$ by $W$ to get $XW$

Operation 2: Add the the bias vector $c$ to get $XW + c$

Operation 3: Apply ReLU

Operation 4: Resulting matrix from ReLU is multiplied by the weight matrix and passed on as output.

The result due to these operations is as follows:

$$
X = \begin{bmatrix}
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 
\end{bmatrix} \\[0.2cm]

\implies XW = \begin{bmatrix}
0 & 0 \\
0 & 1 \\
1 & 0 \\
1 & 1 
\end{bmatrix}

\times

\begin{bmatrix}
1 & 1 \\
1 & 1 
\end{bmatrix}\\[0.2cm]
= \begin{bmatrix}
0 & -1 \\
1 & 1 \\
1 & 1 \\
2 & 2
\end{bmatrix}\\[0.2cm]

\implies XW + c  = \begin{bmatrix}
0 & -1 \\
1 & 0 \\
1 & 0 \\
2 & 1
\end{bmatrix}\\[0.2cm]

\implies ReLU(XW + c) = \begin{bmatrix}
0 & 0 \\
1 & 0 \\
1 & 0 \\
2 & 1 
\end{bmatrix}

\\[0.2cm]

\implies ReLU(XW + c) \times w =

\begin{bmatrix}
0 & 0 \\
1 & 0 \\
1 & 0 \\
2 & 1
\end{bmatrix}

\times

\begin{bmatrix}
1 \\
-2
\end{bmatrix}\\[0.2cm]

\therefore Output =
\begin{bmatrix}
0 \\
1 \\
1 \\
0
\end{bmatrix}

$$

### Code for computation of the normal equation

In [24]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
X_t = np.array([[0, 0, 1, 1], [0, 1, 0, 1], [1, 1, 1, 1]])
result = np.dot(X_t, X)
print(result)

[[2 1 2]
 [1 2 2]
 [2 2 4]]


In [25]:
# Computing Inverse of (X_tX)
prod_1 = np.linalg.inv(result)
print(prod_1)

[[ 1.00 -0.00 -0.50]
 [ 0.00  1.00 -0.50]
 [-0.50 -0.50  0.75]]


In [26]:
# Computing (X_t)y
y = np.array([[0], [1], [1], [0]])
prod_2 = np.matmul(X_t, y)
print(prod_2)

[[1]
 [1]
 [2]]


In [27]:
# Computing the parameter and bias vector,
w = np.matmul(prod_1, prod_2)
print(w)

[[0.00]
 [0.00]
 [0.50]]
