In [2]:
import tensorflow as tf

In [3]:
x_1 = tf.Variable(initial_value=[1.0, 2.0])
x_2 = tf.Variable(initial_value=[1.2, 2.0])

with tf.GradientTape() as tape:
    f = x_1 * x_2
gradient = tape.gradient(f, [x_1, x_2])
print(gradient)

[<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 2. ], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>]


In [6]:
x = tf.linspace(-10.0, 10.0, 10)
delta = tf.Variable(0.0)

with tf.GradientTape() as tape:
  y = tf.nn.sigmoid(x+delta)

dy_dx = tape.jacobian(y, delta)

In [7]:
dy_dx

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([4.5395806e-05, 4.1859134e-04, 3.8362022e-03, 3.3258736e-02,
       1.8632649e-01, 1.8632641e-01, 3.3258699e-02, 3.8362255e-03,
       4.1854731e-04, 4.5416677e-05], dtype=float32)>